server:
  port: 8080
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          # 注意如果locator.enabled为true，且locator.lower-case-service-id为true时，路由规则配置将不生效
          lower-case-service-id: false
          enabled: true
      routes:
        - id: time_between
          uri: lb://client-a
          predicates:
            - Path=/client-a/**
            - TimeBetween=上午9:00, 下午2:00
          filters:
            - StripPrefix=1
logging:
  level:
    reactor.netty: debug
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8686/eureka

