server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://localhost:8081
          predicates:
            - Path=/client-a/**
            - After=2021-01-09T13:55:42.077+08:00[Asia/Shanghai]
          filters:
            - StripPrefix=1
  application:
    name: gateway-server
logging:
  level:
    reactor.netty: debug
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
