// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HiService.proto

package com.yicj.study.grpc.model;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yicj.study.grpc.model.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
