// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HiService.proto

package com.yicj.study.grpc.model;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yicj.study.grpc.model.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>repeated string hobbies = 3;</code>
   * @return A list containing the hobbies.
   */
  java.util.List<java.lang.String>
      getHobbiesList();
  /**
   * <code>repeated string hobbies = 3;</code>
   * @return The count of hobbies.
   */
  int getHobbiesCount();
  /**
   * <code>repeated string hobbies = 3;</code>
   * @param index The index of the element to return.
   * @return The hobbies at the given index.
   */
  java.lang.String getHobbies(int index);
  /**
   * <code>repeated string hobbies = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the hobbies at the given index.
   */
  com.google.protobuf.ByteString
      getHobbiesBytes(int index);

  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  int getTagsCount();
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  boolean containsTags(
      java.lang.String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTags();
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTagsMap();
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */

  java.lang.String getTagsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */

  java.lang.String getTagsOrThrow(
      java.lang.String key);
}
