server:
  port: 2001
eureka:
  instance:
    hostname: eureka-center
  client:
    serviceUrl:
      defaultZone: http://localhost:2001/eureka #每个服务都有一个地址，用于集群之间的通信，默认为 localhost:8761/eureka
    register-with-eureka: false # 是否将自己注册到eureka服务中心，
    fetch-registry: false # 是否从eureka中获取注册信息，因为自己是注册中心，不会从该应用中检索注册信息
spring:
  application:
    name: eureka-ceneter

logging:
  level:
    root: debug