server:
  port: 8080
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: test
          uri: http://news.baidu.com/
          predicates:
            - Path=/test/**
        - id: juejin
          uri: https://juejin.im/user/5aa50b96f265da23866f836e
          predicates:
            - Path=/juejin/**