server:
  port: 8080
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: client-a
          uri: http://localhost:8081
          predicates:
            - Path=/client-a/**
            - TimeBetween=上午9:00, 下午2:00
          filters:
            - StripPrefix=1
logging:
  level:
    reactor.netty: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8686/eureka
